name: ✨ Feature Request
description: Suggest an idea to help us improve
title: "[Feature]"
labels: ["enhancement"]
assignees:
  - hoho4190

# https://github.com/wandb/wandb/blob/main/.github/ISSUE_TEMPLATE/feature-request.yml

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A clear and concise description of the feature you're interested in.
    validations:
      required: true

  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested Solution
      description: |
        Describe the solution you'd like.
        A clear and concise description of what you want to happen.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: |
        Describe alternatives you've considered.
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
    validations:
      required: false
